### ISSUE TITLE
primer clipping for polio virus 

### ISSUE THREAD

**Issue by NmnBttr** [rki-mf1/CoVpipe2#66]
First of all thank you for this great pipeline. I am currently trying to apply CoVpipe2 on Polio virus data. After adjusting the input data I was able to run the pipeline. The results came out good with all the output files, plots and reports, however the primer clipping seems to not work. I searched the primer sequences in both clipped and non clipped files and they still had the primer sequences.  Can you please help me with this issue? 

For reproducing I included a reference fasta file, primer bed file and a tsv file with the primer sequences. In case a fastq file is needed it can be shared through other channels.
 [Polio1.tar.gz](https://github.com/rki-mf1/CoVpipe2/files/12233097/Polio1.tar.gz)

This is how the pipeline was called

`nextflow run rki-mf1/CoVpipe2 --ref_genome $REF --fastq $WORK_DIR/samplesheet.csv --list --cores 4 --max_cores 8 -r v0.4.2 -profile local,docker --primer_bed $PRIMER`

Thank you in advance!

**Comment by MarieLataretu** [comment]
Hi @NmnBttr ,

cool nice to hear!
As I understand the pipeline run successfully without errors, correct?

Do you have by chance a IGV screenshot (shared through other channels if sensitive)? Or how did you search for the primer sequences in the BAM files directly?

**Comment by NmnBttr** [comment]
Hi @MarieLataretu,

thank you for the quick reply! Yes the pipeline runs without any error. I can share you an IGV screenshot through email if that's okay. I also searched for the primer sequences not in the bam files directly but I converted them using samtools into fastq files then I used grep to search for the primer sequences.
